"""Audit-grade probabilistic valuation primitives.

The package is deliberately pure Python and side-effect free. It cannot write
BigQuery, invoke brokers, call LLMs or promote a valuation to production.
"""

from .calibration import (
    CalibrationBin,
    IntervalCalibrationReport,
    IntervalForecast,
    ModelCalibrationEvidence,
    ProbabilityCalibrationReport,
    ProbabilityForecast,
    RiskCalibrationEvidence,
    apply_conformal_interval,
    bind_model_calibration,
    bind_risk_calibration,
    calibration_evidence_hash,
    conformal_absolute_error,
    interval_calibration_report,
    probability_calibration_report,
    verify_model_calibration_registry,
    verify_risk_calibration_registry,
)
from .ensemble import combine_valuation_models
from .intrinsic import (
    DCF_MODEL_VERSION,
    RESIDUAL_INCOME_MODEL_VERSION,
    DcfScenario,
    ResidualIncomeScenario,
    ReverseDcfResult,
    build_dcf_configuration_hash,
    build_residual_income_configuration_hash,
    dcf_scenario_distribution,
    discounted_cash_flow_value,
    residual_income_distribution,
    residual_income_value,
    reverse_dcf_growth,
)
from .models import (
    Applicability,
    CalibrationStatus,
    ModelDistribution,
    PriceObservation,
    QualityAssessment,
    QualityState,
    RiskState,
    ValuationError,
    ValuationLineage,
    ValuationResult,
    ValuationState,
)
from .policy import ValuationPolicy, load_policy
from .quality import (
    QUALITY_CONFIGURATION,
    QUALITY_CONFIGURATION_HASH,
    QUALITY_MODEL_VERSION,
    QualityInputs,
    assess_quality,
)
from .relative import (
    RELATIVE_MODEL_VERSION,
    PeerObservation,
    RelativeMetric,
    RelativeSubject,
    RelativeValuationEstimate,
    build_peer_universe_hash,
    build_relative_configuration_hash,
    estimate_relative_value,
)
from .routing import (
    EntityType,
    ROUTES,
    RouteDefinition,
    RouteValidation,
    validate_model_route,
)

__all__ = [
    "Applicability",
    "CalibrationBin",
    "CalibrationStatus",
    "DCF_MODEL_VERSION",
    "DcfScenario",
    "EntityType",
    "IntervalCalibrationReport",
    "IntervalForecast",
    "ModelCalibrationEvidence",
    "ModelDistribution",
    "PeerObservation",
    "PriceObservation",
    "ProbabilityCalibrationReport",
    "ProbabilityForecast",
    "QUALITY_CONFIGURATION",
    "QUALITY_CONFIGURATION_HASH",
    "QUALITY_MODEL_VERSION",
    "QualityAssessment",
    "QualityInputs",
    "QualityState",
    "RELATIVE_MODEL_VERSION",
    "RESIDUAL_INCOME_MODEL_VERSION",
    "ROUTES",
    "RelativeMetric",
    "RelativeSubject",
    "RelativeValuationEstimate",
    "ResidualIncomeScenario",
    "ReverseDcfResult",
    "RiskCalibrationEvidence",
    "RiskState",
    "RouteDefinition",
    "RouteValidation",
    "ValuationError",
    "ValuationLineage",
    "ValuationPolicy",
    "ValuationResult",
    "ValuationState",
    "apply_conformal_interval",
    "assess_quality",
    "bind_model_calibration",
    "bind_risk_calibration",
    "build_dcf_configuration_hash",
    "build_peer_universe_hash",
    "build_relative_configuration_hash",
    "build_residual_income_configuration_hash",
    "calibration_evidence_hash",
    "combine_valuation_models",
    "conformal_absolute_error",
    "dcf_scenario_distribution",
    "discounted_cash_flow_value",
    "estimate_relative_value",
    "interval_calibration_report",
    "load_policy",
    "probability_calibration_report",
    "residual_income_distribution",
    "residual_income_value",
    "reverse_dcf_growth",
    "validate_model_route",
    "verify_model_calibration_registry",
    "verify_risk_calibration_registry",
]
