name: Deploy Cloud Function

# Evento que activa el workflow: pull request cerrado (merged) en la rama master
on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  deploy:
    if: github.event.pull_request.merged == true  # Solo ejecuta si el PR fue mergeado
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Install dependencies
        run: |
          pip install -r cloud-functions/daily_stocks/requirements.txt
      
      - name: Deploy to Cloud Functions
        run: |
          gcloud run deploy stockdaily \
              --source ./cloud-functions/daily_stocks \
              --platform managed \
              --region us-east1 \
              --allow-unauthenticated \
              --set-env-vars TICKERS="AAPL" 
